export const UPDATE_POSTS = "UPDATE_POSTS";
export const REMOVE_POST = "REMOVE_POST";
export const SET_CURRENT_POST = "SET_CURRENT_POST";
export const ADD_POST = "ADD_POST";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";

export const ADD_MEMBER = "ADD_MEMBER";
export const UPDATE_MEMBERS = "UPDATE_MEMBERS";
export const REMOVE_MEMBER = "REMOVE_MEMBER";
export const SET_CURRENT_MEMBER = "SET_CURRENT_MEMBER";

export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_DESTINATION = "UPDATE_DESTINATION";